# Generated by Django 4.0.3 on 2022-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='company.contact'),
        ),
        migrations.AddField(
            model_name='location',
            name='spaces',
            field=models.ManyToManyField(blank=True, to='company.space'),
        ),
    ]
